### ISSUE TITLE
임포팅한 라이브러리에 문제가 있습니다.

### ISSUE THREAD

**Issue by yusa-imit** [Capstone-202002/Pathfinder#20]
새로 임포팅한

**electron-titlebar-react-component**

라이브러리의 

window minimize function이 제대로 작동하지 않는 느낌인데 혹시 시간 남으시는 분 계시면 라이브러리 파일 확인 부탁드립니다. 👍 

아무도 시간이 안남으시면 거의 막바지에 해결해보겠습니다
- [x] 해결

**Comment by RE-A** [comment]
테스트 결과, 일단 최소화(창을 아래의 작업 표시줄로 보내는 거)/ 최대화에는 문제는 없음. 대신, 사이즈 조절(최대화, 원래 크기)에는 문제가 있어서 항상 최대 크기로 고정이 됨.  

일단 헷갈리는거 방지하기 위해 함수 정의를 제대로 짚고 감.
minimize => 최소화. 작업 표시줄로 보내버리는거
maximize => 최대화. 프로그램을 화면 꽉 채우는거
unmaximize => 원상 복구. 프로그램을 원래 크기의 창으로 다시 돌리는거  

![image](https://user-images.githubusercontent.com/11948404/97049606-f430c480-15b6-11eb-8763-c2e8540a58d2.png)

TitleBarMac의 소스코드를 보면 다음과 같은데, 윈도우 사이즈 조절에 maximize(), unmaximize()가 사용되고 있는데, 콘솔에서 테스트 해본 결과 이 함수들이 제대로 작동하지 않고 있음. 검색해보니 일렉트론에서 이런 문제를 겪는 사람들이 좀 있었고, 나는 대신 아래의 함수를 사용해 봤는데 의도한 대로 작동됨.   

![image](https://user-images.githubusercontent.com/11948404/97049861-57baf200-15b7-11eb-90ab-52fc66af41d9.png)

개인적으로, 라이브러리 자체의 버그로 추정되고 소스 코드를 보니 UI만 따오면 기능 자체는 어렵지 않아서 다른 라이브러리를 찾거나, 직접 구현하는걸 권함. 몇개 테스트를 해보니, isMaximized() 가 항상 false로 고정되어 있어서 maximize 관련 함수가 작동하지 않음.
