### ISSUE TITLE
2020/09/08 발표 피드백

### ISSUE THREAD

**Issue by yusa-imit** [Capstone-202002/Pathfinder#3]
폴더 기능은 좋았다?
의도와 결과물이 매칭이 잘 안된다
난이도가 떨어진다
대쉬보드 필요성 및 사용성 제공 고민?

**Comment by yusa-imit** [comment]
//난이도

앱 - 백그라운드 어플리케이션(다운로드, 전체 색인 목록 생성)
디렉토리 검색 알고리즘

**Comment by yusa-imit** [comment]
대시보드 제거

**Comment by RE-A** [comment]
한달 지난거라 필요없으니 닫음
