### ISSUE TITLE
9/13 회의

### ISSUE THREAD

**Issue by Kynel** [Capstone-202002/Pathfinder#4]
멘토님 피드백중에서

제안한 목적이 애매하다?
개발의 목표와 목적
1. 쓸데없이 방치되어 용량을 낭비하는 파일들이 상당히 많다.
2. 다운로드 받은 파일들을 관리하기 힘들고, 1번과 비슷한 문제가 생긴다
3. 파일 탐색기의 기능이 일괄적으로 파일들을 변경하는데에 쉽지 않다.
4. 파일 검색이 너무 느리고, 기능이 부족하다.

해결책
1. 전체 파일 중에서 최근 몇개월동안 사용되지 않은 파일들을 정리
2. 사용자가 파일을 다운받고 난 뒤, 일정 시간이 지나면 리스트하여 일괄 삭제를 할 수 있게 (필터링, 선택 등)
3. 그에 대한 기능들 제공
4. DB에 파일에 대한 정보(이름, 기타등등)을 색인하여 빠르고 쉬운 검색 제공

--------------------------

생각중인 기능 들 

- 사용자가 정리를 직접 해야한다?
  - 자동정리!
-

**Comment by RE-A** [comment]
0. 대시보드에서 자주 찾는 폴더/가상폴더 뷰로 변경

1. 이름/내용/확장자 기반 필터링 (3번과 연계)
2. 가상 디렉토리 ( 여러 디렉토리의 파일들을 하나의 뷰에서 볼 수 있도록)
3. 색인 기반 검색 (DB 활용) (백그라운드에서 색인 진행/ 메인 프로그램 돌리는데 지장 없게)
4. 압축 기반 임시 휴지통(압축 알고리즘 선택해야함 압축률 높은거.. zip은 낮을거임).
삭제할 시 바로 삭제하지 않고 압축 등의 방법으로 최대한 파일 크기를 줄인 채로 저장. 일정 기간이 지나면 삭제.
그 전에 사용자가 복구 가능.

5. 다운로드된 파일, 정리되지 않은 채로 일정 기간이 지나면 일괄 삭제
6. 다운로드된 파일들(카카오톡 받은 파일, 인터넷 파일 등등) 전부 자동 분류. 인터넷 파일들도 시스템 콜 이용해서 자동 분류

**Comment by Kynel** [comment]
진행 완료
