### ISSUE TITLE
9/16 회의 및 숙제

### ISSUE THREAD

**Issue by Kynel** [Capstone-202002/Pathfinder#5]
### 타겟층
헤비 유저(ssd나 hdd를 여러개를 보유하고 있고, 많은 양의 파일을 복잡한 디렉토리 구조로 정리해야 하고, 그것을 편하게 찾아서 이용할 수 있어야 하는 사람들) ex - 크리에이터, 헤비 다운로더, 개발자
### 기능
1.  다운로드 파일 분류 지원(feat. ML) -> NLP.js 이용 or tensorflow for js 등 여러 방법 논의
2.  규칙을 지정하여 디렉토리 자동 구조화 -> 파일 디렉토리를 마인드맵 같은 구조로 쉽게 생성후, 이름이 정리된 파일들을 분류해줌 + 파일 이름을 일괄적으로 쉽게 변경할 수 있는 기능 제공
### 부가기능
1.  기능2를 도와줄 수 있는 디렉토리 시각화 -> 기존에 반응 좋았던 그 'view'로
2.  기능1을 도와줄 수 잇는 확장프로그램 or 다운로드 매니저
3.  기능2에서 정리된 내용을 쉽게 활용할 수 있는 가상 디렉토리 ex) 소팅, 검색, 필터링
### 논의사항
1.  기능2를 사용자가 어떠한 시각화를 통하여 사용할 건지 -> 뷰는 이대로, 드래그 앤 드롭 과 같은 기능 추가
2.  크롬 확장프로그램 or 다운로드 매니저
### 추가사항
1.  기능2를 사용할 때 사용할  수 있는 DB를 활요한 색인 을 할 예정이다

------------------------

### 숙제
준: 페이지 하나 라우팅하여 아무거나 띄우기
홍: 디렉토리 페이지 배치 try
호: 빌드 터지는거 고쳐오기

**Comment by RE-A** [comment]
다했음
