### ISSUE TITLE
컴포넌트 및 HOOK 구조

### ISSUE THREAD

**Issue by Kynel** [Capstone-202002/Pathfinder#9]
### 1. 렌더 -> 메인프로세스 요청 및 응답 - 디렉토리 시각화
- #### (렌더 요청) -> (메인프로세스 응답) 의 형식 (편의상 이렇게 둿음, 메소드 호출로 처리)
- (디렉토리) -> (해당 디렉토리의 파일리스트, 각 파일들의 확장자 및 폴더여부, 각 파일들의 정보-파일명,위치,확장자,용량,(폴더라면)하위파일갯수)
- (디렉토리, 파일및폴더이름) -> (해당파일의 정보-파일명,위치,확장자,용량,(폴더라면)하위파일갯수)
- (디렉토리, 파일및폴더이름, 새 이름) -> (해당파일의 이름변경 완료되었다는 콜백)                      - 
- (디렉토리, 파일및폴더이름, 새 위치) -> (해당파일 및 폴더의 위치변경 완료되었다는 콜백)         - 여러 파일을 옮기면 시간이 걸릴수 있는데, 그것도 처리를 해야대는데...
----------------------------------------------------------
#### base: 기본 템플릿(pure component)
  - MenuBar: 왼쪽의 슬라이드 메뉴바, 아이콘/기능/
  - Header: 기능명을 담당 상단바
  - Panel: 기능을 위한 도화지
#### Visualization(디렉토리 시각화)
global state: section(화면에 표시될 내용에 대한 정보), current_dir(정보 표시할 dir), filter_info(필터 정보), 
- StatusBar: 현재 디렉토리, 뒤로가기 및 앞으로가기, 상위 디렉토리 이동
- SettingBar: 디렉토리 초기위치 설정, 탐색내용 초기화, 필터, 파일이름 일괄변경등 주요로직이 들어갈 예정
##### 하위 컴포넌트
- Section: 한 디렉토리에 대한 정보, 여래개의 section이 모여서 Visualization을 구성
- Element: 한 개의 파일/폴더에 대한 정보, 여러개의 Element가 모여서 Section을 구성. 내장 메소드로 파일이름 변경 과 같은 기능을 수행할 것. 내부 state로 파일명, 위치, 확장자, 용량, (폴더라면)하위파일갯수 등

**Comment by RE-A** [comment]
* `(디렉토리, 파일및폴더이름, 새 위치) -> (해당파일 및 폴더의 위치변경 완료되었다는 콜백) - 여러 파일을 옮기면 시간이 걸릴수 있는데, 그것도 처리를 해야대는데...`

이런 작업은 백그라운드에서 진행시키고 완료콜백으로 팝업같은거 날리는 방식이 좋을 듯. 내가 말한 최적화가 이런 코스트 큰 작업을 걸러내서 백으로 돌리는거

**Comment by Kynel** [comment]
진행 완료
